### ISSUE TITLE
align error with example data.

### ISSUE THREAD

**Issue by Jomagrax** [foerstner-lab/READemption#23]
Hi everyone, It's my first time using READemption and Im having some trouble with the align fuction.

Im following the [tutorial ](https://reademption.readthedocs.io/en/latest/example_analysis.html) and working on version 0.5.0

` reademption align -f READemption_analysis_prueba -p 8  --poly_a_clipping`

```
[E::hts_open_format] Failed to open file READemption_analysis_prueba/output/align/alignments/InSPI2_R1_alignments_final.bam
Traceback (most recent call last):
  File "/home/superuser/miniconda3/bin/reademption", line 316, in <module>
    main()
  File "/home/superuser/miniconda3/bin/reademption", line 280, in main
    args.func(controller)
  File "/home/superuser/miniconda3/bin/reademption", line 290, in align_reads
    controller.align_reads()
  File "/home/superuser/miniconda3/lib/python3.7/site-packages/reademptionlib/controller.py", line 81, in align_reads
    self._align_single_end_reads()
  File "/home/superuser/miniconda3/lib/python3.7/site-packages/reademptionlib/controller.py", line 327, in _align_single_end_reads
    paired_end=False)
  File "/home/superuser/miniconda3/lib/python3.7/site-packages/reademptionlib/readaligner.py", line 20, in run_alignment
    paired_end=paired_end)
  File "/home/superuser/miniconda3/lib/python3.7/site-packages/reademptionlib/segemehl.py", line 69, in align_reads
    pysam.sort("-o", tmp_sorted_outfile, output_file)
  File "/home/superuser/miniconda3/lib/python3.7/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools sort: can\'t open "READemption_analysis_prueba/output/align/alignments/InSPI2_R1_alignments_final.bam": No such file or directory\n
```

Let me know If there's any additional information you need. Thanks in advance, Jose.

**Comment by Tillsa** [comment]
Hi Jose,
Thanks for reporting this error!
Could you please post which files are inside the folder "READemption_analysis_prueba/output/align/alignments/"
Best regards,
Till

**Comment by Jomagrax** [comment]
Hi @Tillsa, Thanks for your response, here's the folder
` ls -l  READemption_analysis_prueba/output/align/alignments/
total 0`

**Comment by Tillsa** [comment]
Did you use segemehl 0.2.0 or 0.3.4?

**Comment by Jomagrax** [comment]
I have 0.2.0, as expalined [here](https://reademption.readthedocs.io/en/latest/installation.html)
`curl www.bioinf.uni-leipzig.de/Software/segemehl/old/segemehl_0_2_0.tar.gz > segemehl_0_2_0.tar.gz
tar xzf segemehl_0_2_0.tar.gz
cd segemehl_*/segemehl/ && make && cd ../../`

**Comment by Tillsa** [comment]
Could you please install segemehl 0.3.4 and and add it to the path instead of 0.2.0 and then run the analysis again? Does that fix the error?

**Comment by Haley-Wami** [comment]
Hello again Tillsa,

I got the same error while testing the READemption.
I installed and tried using both segemehl versions (0.2.0 and 0.3.4) here are the errors I get from the tests.

=================== short test summary info ============================
FAILED tests/test_paths.py::TestPaths::test_set_read_files_dep_file_lists - AttributeError: 'Paths' object has no attribute 'primary_read_aligner_sam_paths'
FAILED tests/test_segemehl.py::TestSegemehlAligning::test_align_reads_single_read_perfect_match - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
FAILED tests/test_segemehl.py::TestSegemehlAligning::test_map_reads_single_read_not_matching - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
FAILED tests/test_segemehl.py::TestSegemehlAligning::test_map_reads_single_read_one_mismatch - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
FAILED tests/test_segemehl.py::TestSegemehlAligning::test_map_reads_single_read_three_mismatches - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
FAILED tests/test_segemehl.py::TestSegemehlAligning::test_map_reads_single_read_two_mismatches_90 - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
FAILED tests/test_segemehl.py::TestSegemehlAligning::test_map_reads_single_read_two_mismatches_95 - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
FAILED tests/test_segemehl.py::TestSegemehlAligning::test_map_reads_single_too_short_read - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

When using the 0.3.4 version I get the same errors, except one error with test_controller.py seems to be fixed. 
(FAILED tests/test_controller.py::TestControllerReadAligning::test_read_aligning - pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools sort: can\'t open "a_test_project/output/...) 

Many thanks in advance!

**Comment by Tillsa** [comment]
Hi!
The tests are failing because of the to the switch from segemehl v0.2.0 to v0.3.4. I am adjusting the tests right now, but it takes some time. However, READemption v0.5.0 should be functional right now although the tests are failing.
I'll get back to this issue thread once the tests are solved.
Best,
Till

**Comment by Haley-Wami** [comment]
Thanks a lot Till! :)

**Comment by Tillsa** [comment]
Hi @Haley-Wami @Jomagrax 
We just released version 0.6.0 that should fix the occurring errors. Feel free to try it and let me know if you still have problems.
Best regards,
Till

**Comment by Haley-Wami** [comment]
Hi Till,
The new version works perfectly. Many thanks!
Kind Regards,
Haley

**Comment by Tillsa** [comment]
Great!
