### ISSUE TITLE
Update docker image to the latest version

### ISSUE THREAD

**Issue by mdphan** [foerstner-lab/READemption#31]
Hi, 

I would like to try READemption and using docker is a great option for me. However, I notice that the latest version on https://registry.hub.docker.com/r/konradfoerstner/reademption is 0.4.0. Are you planning to update the docker image to the latest version?

Best regards,
Duy

**Comment by Tillsa** [comment]
Hi Duy,

Yes we are planning to update the docker image. But it may take some time since we are developing a new version right now.

Best wishes,
Till
