### ISSUE TITLE
align error (probably segemehl version issue)

### ISSUE THREAD

**Issue by npokorzynski** [foerstner-lab/READemption#32]
Hi, 

I'm trying to run READemption on MacOS 11.2.3 with python 3.8.3. 

My primary question is whether or not segemehl 0.3.4 is compatible with MacOS. The reason being that I'm having issues with the align subcommand in READemption. When I run align, I get errors similar to those posted here previously with various .bam files not being found during alignment. Past suggestions have been to update segemehl to 0.3.4, but conda apparently doesnt support 0.3.4 for MacOS. 

I've tried running the other command line segemehl installs but I'm somewhat of a novice and cant get them to work. Any help would be appreciated!

All the best,
Nick

**Comment by Tillsa** [comment]
Hello Nick,

You can install segemehl 0.3.4 from source (that is without using conda). Instructions can be found here: 

https://reademption.readthedocs.io/en/latest/installation.html#install-segemehl

Best regards,

Till

**Comment by npokorzynski** [comment]
Hi @Tillsa, thanks for the quick reply - 

That is the other command line installs I was referencing, I cant seem to get it to work. Every time I try the install, I get a "no such file or directory" error - in particular for the following script:

cd segemehl_*/segemehl*/ && make all && cd ../../

I'm certain that this is an issue with me not understanding the basics here, but perhaps you can explain what I need to provide/satisfy to get this to work?

Thanks,
Nick

**Comment by Tillsa** [comment]
Hello Nick,

Make sure you are inside the folder "segemehl-0.3.4". You can go there with the command "cd". Once inside this folder there is a file called "Makefile". You are executing this Makefile with the command "make all", which will install segemehl for you. Just type "make all" inside the folder "segemehl-0.3.4". Afterwards you need to add the file "segemehl.x" that is inside the folder "segemehl-0.3.4" to your PATH. There are numerous tutorials on how to add files to the PATH e.g. this one https://wpbeaches.com/how-to-add-to-the-shell-path-in-macos-using-terminal/

Best regards,

Till

**Comment by npokorzynski** [comment]
@Tillsa 

Thanks for the advice. 

So, I can download the segemehl-0.3.4 folder but I'm running into the following problems. 

If I run the provided code on the READemption website, substituting a location in my path as below: 

`cd segemehl_*/segemehl*/ && make all && cd usr/local/bin`

I get the following error:  `segemehl_*/segemehl*/: No such file or directory`

Am I supposed to replace the asterisks with something more relevant? 

If I just run `make all` by itself, I get this error: 

`/bin/sh: pkg-config: command not found
In file included from libs/match.c:36:
In file included from include/match.h:34:
include/segemehl.h:54:10: fatal error: 'htslib/sam.h' file not found
#include "htslib/sam.h"`

I'm not sure what the issue is; I'm within the segemehl-0.3.4 folder.

**Comment by npokorzynski** [comment]
Hi @Tillsa I just wanted to ping this and see if you had any further advice or suggestions. 

Thanks,
Nick

**Comment by Tillsa** [comment]
Hi Nick,

It looks like you need to install htslib and samtools. This tutorial should help you: https://www.biostars.org/p/328831/ 

Best regards,

Till

**Comment by npokorzynski** [comment]
@Tillsa 

As noted in my previous post, I've attempted installing/re-installing htslib and samtools and I get the same errors. Does "include htslib/sam.h" mean anything to you specifically? For example, do I need to relocate htslib/samtools files to the segemehl folder? I'm not sure what to do and google hasnt been very helpful in this regard. 

Thanks,
Nick

**Comment by Tillsa** [comment]
Hi Nick, 

I am not sure why the error persists. But I assume your installed htslib but the executables werent't added to the PATH. I would try adding 'htslib/sam.h' to the PATH and maybe also to the PKG_CONFIG_PATH environment variable like it is suggested here https://www.bioinf.uni-leipzig.de/Software/segemehl/#installation

Best regards,

Till
