### ISSUE TITLE
Metatranscriptome

### ISSUE THREAD

**Issue by Thexiyang** [foerstner-lab/READemption#38]
Thanks for this nice tool! Is this tool applicable for metatranscriptomic analysis?

**Comment by konrad** [comment]
Thanks for your feedback and your question, @Thexiyang. READemption has been used in a transcriptome analysis ([Krohn et al., 2017](https://doi.org/10.3389/fmicb.2017.01941)). I would be a little bit cautions but it could work depending on your project.
