### ISSUE TITLE
[Feature request] Log

### ISSUE THREAD

**Issue by almutwerner** [foerstner-lab/READemption#40]
Hello!

Could you make the screen output when running reademption a bit more talkative? 

I was running the align subcommand on a paired file, and only got a python error, that samtools couldn't read the header of the empty bam file. But running segemehl on it's own revealed, that it was actually a problem of query and mate having different sizes.

It would be really helpful to have that information directly with the screen output of reademption. Or, if that is too bothersome, have a logfile created with each subcommand, that contains the entire screen output of all the tools used in that command.

**Comment by Tillsa** [comment]
Hello,
Thank you for your feedback. READemption has the flag --progress for the align command. Would this have shown the the segemehl error?
