### ISSUE TITLE
Align subcommand mysteriously takes forever in some runs in ver. 2.0.0

### ISSUE THREAD

**Issue by elhossary** [foerstner-lab/READemption#41]
Some of the runs went without problems. but there are some runs had issues with no error message produced.
But the observation is:
The alignment runs normally until segemehl log message "Goodbye." then the it abonormaly takes forever with no finsih, no matter the size of the data
When I iterrupted the run, bam files produced but the stats files were not produced.
Most propably, the program hangs at the endings of "concurrent" processes. may be the process pool does not close?
I also got in one of the runs this message:
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by Tillsa** [comment]
Can you please post the complete align command, the output of tree of the analysis folder before running align and the error message?

**Comment by Tillsa** [comment]
Fixed in version 2.0.2
